### ISSUE TITLE
Use _.runInContext

### ISSUE THREAD

**Issue by jdalton** [SeanJM/lodash.getArguments#1]
In node-land it's useful to use [_.runInContext](https://lodash.com/docs#runInContext) to avoid augmenting the primary `lodash` package.

``` js
var _ = require('lodash').runInContext();
_.mixin(....);
module.exports = _;
```

**Comment by SeanJM** [comment]
If augmenting the lodash package is such a concern, why not separate the function completely? I am ignorant when it comes to node. 

``` javascript
function getArguments(list, predicates) {
  var i,
      n,
      b,
      k,
      o = {};
  list = Array.prototype.slice.call(list);
  for (i = 0, n = list.length; i < n; i++) {
    for (k in predicates) {
      if (typeof predicates[k] === 'function') {
        b = predicates[k](list[i], i, n);
        if (b) {
          o[k] = list[i];
        }
      }
    }
  }
  for (k in predicates) {
    if (typeof o[k] === 'undefined') {
      o[k] = false;
    }
  }
  return o;
}
```

**Comment by jdalton** [comment]
> If augmenting the lodash package is such a concern, why not separate the function completely

You could if you wanted. 

You could also use lodash a bit more if you want too with smth like:

``` js
function getArguments(list, predicates) {
  var o = _.mapValues(predicates, _.constant(false));
  return _.transform(list, function(o, value) {
    _.forIn(predicates, function(predicate, key) {
     if (predicate(value, index, list.length)) {
       o[key] = value;
     }
   });
  }, o);
}
```

**Comment by SeanJM** [comment]
That is elegant. :+1:

**Comment by SeanJM** [comment]
Before I close this. What is a viable solution to your initial problem?

**Comment by jdalton** [comment]
> Before I close this. What is a viable solution to your initial problem?

It depends on what your target platform is. If you're planning this to work in the browser & node then there's a bit of UMD to juggle.

**Comment by SeanJM** [comment]
I'm basically asking you what you want. :8ball:

**Comment by jdalton** [comment]
Ah, more than anything just letting you know you can use `_.runInContext`.
If it's appropriate for your extension then rock, if not that's ok too.
